### ISSUE TITLE
Diagrams and demo video

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild-folder-to-folder#36]
Review feedback from Dinis and create pending diagram and video:

1.- Update diagrams of the flow  
2.- Create diagram for the setup process
3.- Diagram on how the components (using those ids in the diagram) relate to each other (Service OVA, User OVA, EFS)
4.- End to end video

**Comment by MaNe2020** [comment]
@GINAGC I think this is not blocked.
I verified work done by @pranaysahith and created PR.
Will update diagram and add video by end of this week.
@aduvukace FYI

**Comment by MaNe2020** [comment]
1. Flow diagram: https://user-images.githubusercontent.com/70108899/106617806-3a5ed200-656f-11eb-851a-530136d3a68c.PNG
2. Setup process diagram: https://user-images.githubusercontent.com/70108899/108490947-9b8ee100-72a3-11eb-8af8-3582db3210ba.png
3. Components correlation diagram: 
https://user-images.githubusercontent.com/70108899/106618748-19e34780-6570-11eb-8b06-43336c593604.PNG
4. Videos:
- setup: https://www.loom.com/share/641eccabe35047e082a5d5c788bc8119
- use: https://www.loom.com/share/c710beedaeee43e5a0907d9fcaf10d44

@GINAGC let me know if anything else needs to be done here.
@aduvukace FYI

**Comment by GINAGC** [comment]
@MaNe2020 great work!!

For the videos, can we have this one on better quality? https://www.loom.com/share/c710beedaeee43e5a0907d9fcaf10d44

Can you also add a components correlation diagram to the instructions?

**Comment by MaNe2020** [comment]
@GINAGC let me work on this and will update you once ready.

**Comment by MaNe2020** [comment]
@GINAGC created PR: https://github.com/k8-proxy/k8-rebuild-folder-to-folder/pull/42 to include components correlation diagram.
And here is video with better quality: https://www.loom.com/share/f6df26f6a6794889a62bda19f1824f2c (it's better if watched on 1.5x speed, same goes for setup one)

Let me know when videos are on yt so I can add them in README

**Comment by GINAGC** [comment]
Thank you, videos sent to edit and youtube process.
