### ISSUE TITLE
defect: detections and imagery

### ISSUE THREAD

**Issue by svf97** [k8-proxy/k8-rebuild-folder-to-folder#48]
.tiff files of unzipped rebuilt file exist both in imagery and main directory
![image](https://user-images.githubusercontent.com/60857664/120111238-7696ed80-c171-11eb-9761-44c67963d83e.png)

**Comment by mohitsengarr** [comment]
I have verified that folder-to-folder application is not using the latest version of rebuild-rest-api. If folder-to-folder and rebuild-rest-api both will be updated to latest version then there will be no issue at all. @GINAGC
