### ISSUE TITLE
errors in logs for successful rebuilds

### ISSUE THREAD

**Issue by svf97** [k8-proxy/k8-rebuild-folder-to-folder#49]
docker logs throw errors even when file is successfully rebuilt. 
[docker_logs.txt](https://github.com/k8-proxy/k8-rebuild-folder-to-folder/files/6566547/docker_logs.txt)

**Comment by llmsjraj** [comment]
@svf97 You are seeing the error logs for successfully processed files because it seems you or someone mistakenly deleted subfolders of `gw-processing` folder in the middle of the processing. While testing please don't access the files of `gw-processing` folder.   @GINAGC

**Comment by mohitsengarr** [comment]
@svf97 you are seeing the error logs for the successful processed files because you or someone have mistakenly deleted the sub-folder of `gw-processing` folder. we should not touch the other folders otherwise it leads to the unexpected behavior. @GINAGC

**Comment by svf97** [comment]
that folder was not deleted at all. actually, one of the things @pranaysahith and I did was to re-mount EFS because the output folder went missing. This means, this happened with gw-processing folder as well.

**Comment by mohitsengarr** [comment]
> @mohitsengarr that folder was not deleted at all. actually, one of the things @pranaysahith and I did was to re-mount EFS because the output folder went missing. This means, this happened with gw-processing folder as well.

thanks @svf97 , My concern was this issue and https://github.com/k8-proxy/k8-rebuild-folder-to-folder/issues/48# both are related to the deployment. Currently, I have checked the folder-to-folder application is not using the latest version of rebuild-rest-api. If folder-to-folder and rebuild-rest-api both will be updated to latest version then there will be no issue at all. @GINAGC
