### ISSUE TITLE
Review possible features to allow them to modify the policies.

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild-folder-to-folder#54]
Review possible features to allow them to modify the policies. Mohit  to comment on the location in the disk of the policy that is used (in the parent OVA and in the docker container).

**Comment by mohitsengarr** [comment]
@pranaysahith we need one more folder `policy` inside the folder `/data/folder-to-folder` and policy JSON should be inside the folder `policy` with file name `policy.json`. @GINAGC
