### ISSUE TITLE
F2F is broken it is giving error when configuring the endpoint

### ISSUE THREAD

**Issue by himanshu2464** [k8-proxy/k8-rebuild-folder-to-folder#60]
@himanshu2464 commented on [Tue Jul 13 2021](https://github.com/k8-proxy/go-k8s-infra/issues/126)

when we do the configuration of IP in F2F and swagger for endpoint it is giving the following error.

![image](https://user-images.githubusercontent.com/45463238/125450680-f64ffc9f-a1d0-43e3-8f84-8a1562abdd25.png)

![image](https://user-images.githubusercontent.com/45463238/125450739-ad91dccd-d35c-48f5-8886-21d92d564782.png)

this happens with the AMI we build from develop branch.

**Comment by himanshu2464** [comment]
this is the older version of F2F and it failed as well, below is the screenshot.
![image](https://user-images.githubusercontent.com/45463238/125454461-8d44f6d4-0caf-41e5-856f-ab9484e028df.png)

**Comment by GINAGC** [comment]
closing as duplicated
